import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {fixture} from './room-fixture.mjs';
import {runnerIds,applyRunnerModel,runnerSummary,encounterCost,buildReceiverDungeon,actualHpPercent,scoreForTarget,DEFAULT_ENCOUNTER} from '../public/flare-s5/game.mjs';
import {encodeInviteCode,decodeInviteCode,makeInviteUrl,inviteCodeFromLocation} from '../public/flare-s5/flow.mjs';
import {Simulation} from '../public/flare-s4/simulation.mjs';

const base={version:1,rules:'web-flare-0.2.0',heroes:{warrior:{name:'Warrior',sprite:'warrior',maxHp:100,damage:12,armor:0,interval:.6,windup:.18,animationTime:.4,range:1.05,speed:4.8,radius:.22}},enemies:{goblin:{name:'Goblin',sprite:'goblin',maxHp:30,damage:5,armor:0,interval:.8,windup:.28,animationTime:.4,range:1.08,radius:.22,gold:6,cost:20,behavior:'guard'},skeleton:{name:'Skeleton',sprite:'skeleton',maxHp:45,damage:7,armor:0,interval:.9,windup:.3,animationTime:.4,range:1.08,radius:.22,gold:9,cost:30,behavior:'guard'}},items:{'small-potion':{name:'Small potion',kind:'heal',heal:10,cost:15}}};
const model={version:1,budget:100,defaultTargetHp:50,defaultRunner:'warrior-l1',runners:{'warrior-l1':{id:'warrior-l1',name:'Rookie Warrior',className:'Warrior',level:1,hero:'warrior',baseHp:100,baseAttack:8,baseDefense:1,weapon:{id:'wooden-club',name:'Wooden Club',attack:4,defense:0}},'warrior-l2':{id:'warrior-l2',name:'Seasoned Warrior',className:'Warrior',level:2,hero:'warrior',baseHp:110,baseAttack:9,baseDefense:2,weapon:{id:'wooden-club',name:'Wooden Club',attack:4,defense:0}},'warrior-l3':{id:'warrior-l3',name:'Tough Warrior',className:'Warrior',level:3,hero:'warrior',baseHp:120,baseAttack:10,baseDefense:3,weapon:{id:'wooden-club',name:'Wooden Club',attack:4,defense:0}}},monsters:{goblin:{name:'Goblin',hp:30,attack:5,defense:1,cost:20,rating:'Light'},skeleton:{name:'Skeleton',hp:45,attack:7,defense:2,cost:30,rating:'Medium'}},items:{'small-potion':{name:'Small Potion',heal:10,cost:15},'spike-trap':{name:'Spike Trap',damage:8,cost:20,oneShot:true}}};
const run=sim=>{sim.start();for(let i=0;i<3600&&sim.status==='running';i++)sim.step();return sim};

test('builder has three governed runner choices',()=>{assert.deepEqual(runnerIds(model),['warrior-l1','warrior-l2','warrior-l3']);const cat=applyRunnerModel(base,model,'warrior-l2'),r=runnerSummary(model,'warrior-l2',cat);assert.deepEqual([r.level,r.hp,r.attack,r.defense],[2,110,13,2])});
test('invite code carries runner and target only in four characters',()=>{const code=encodeInviteCode({runnerId:'warrior-l2',targetHp:55},model),decoded=decodeInviteCode(code,model);assert.equal(code.length,4);assert.deepEqual({...decoded},{runnerId:'warrior-l2',targetHp:55,codeVersion:1})});
test('receiver link uses separate ultra-short g route',()=>{const u=makeInviteUrl('https://think-2-thrive.com/quick-dungeon/flare-s5/',{runnerId:'warrior-l1',targetHp:50},model,{sender:'Buddy'});assert.match(u.href,/^https:\/\/think-2-thrive\.com\/g\/[A-Za-z0-9_-]{4}$/);assert.equal(inviteCodeFromLocation({pathname:u.pathname,search:u.search}),u.pathname.split('/').pop())});
test('percentage scoring works for runners above 100 max HP',()=>{assert.equal(actualHpPercent('cleared',55,110),50);assert.equal(scoreForTarget('cleared',55,50,110),100);assert.equal(scoreForTarget('dead',0,50,110),0)});
test('receiver balanced defaults cost 65 and dungeon is built after invite',()=>{const cat=applyRunnerModel(base,model,'warrior-l2');assert.equal(encounterCost(cat,DEFAULT_ENCOUNTER),65);const built=buildReceiverDungeon({roomId:fixture.id,roomTitle:'Receiver Room',map:fixture,catalog:cat,targetHp:50});assert.equal(built.challenge.room,fixture.id);assert.equal(built.challenge.enemies.length,2);assert.equal(built.spent,65);const sim=run(new Simulation(fixture,built.challenge,cat));assert.ok(['cleared','dead'].includes(sim.status))});
test('sender builder does not choose room or monsters',async()=>{const html=await readFile(new URL('../public/flare-s5/index.html',import.meta.url),'utf8');assert.match(html,/Who must survive\?/);assert.match(html,/CREATE CHALLENGE LINK/);assert.doesNotMatch(html,/id="roomStage"/);assert.doesNotMatch(html,/id="enemy1"/)});
test('receiver opening explains the game before asking for a room',async()=>{const html=await readFile(new URL('../public/flare-s5/challenge.html',import.meta.url),'utf8');assert.match(html,/HOW TO PLAY/);assert.match(html,/Choose a room/);assert.match(html,/Build the danger/);assert.match(html,/closer the finishing HP is to the target/i);assert.match(html,/ACCEPT CHALLENGE/);assert.match(html,/id="roomStage"/)});
test('short-route challenge shell uses canonical root-relative assets',async()=>{const html=await readFile(new URL('../public/flare-s5/challenge.html',import.meta.url),'utf8');assert.match(html,/href="\/quick-dungeon\/flare-s3\/style\.css"/);assert.match(html,/href="\/quick-dungeon\/flare-s5\/style\.css"/);assert.match(html,/src="\/quick-dungeon\/flare-s5\/challenge\.mjs"/);const js=await readFile(new URL('../public/flare-s5/challenge.mjs',import.meta.url),'utf8');assert.match(js,/new URL\('\.\/data\/game\.json',import\.meta\.url\)/)});
