import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
import {parseMap} from '../public/flare-p0/src/core/flare.mjs';
import {S7_ROOMS} from '../public/flare-s71/rooms.mjs';
import {Simulation} from '../public/flare-s71/simulation.mjs';
import {applyRunnerModel,runnerSummary,buildS7Challenge,actualHpPercent,MONSTER_IDS,TRAP_IDS,SUPPORT_IDS} from '../public/flare-s71/game.mjs';
import {calibrateEncounter} from '../public/flare-s71/calibration.mjs';
import {encodeInviteCode,decodeInviteCode,makeInviteUrl,inviteCodeFromLocation,safeSender,inviteSender} from '../public/flare-s71/flow.mjs';
import {heroStanceFrame} from '../public/flare-s71/hero-preview.mjs';

const read=path=>fs.readFileSync(new URL(path,import.meta.url),'utf8'),json=path=>JSON.parse(read(path));
const html=read('../public/flare-s71/challenge.html'),script=read('../public/flare-s71/challenge.mjs'),builder=read('../public/flare-s71/index.html'),builderScript=read('../public/flare-s71/builder.mjs'),preview=read('../public/flare-s71/hero-preview.mjs');
const base=json('../public/flare-p0/data/catalog.json'),model=json('../public/flare-s7/data/game.json');
function roomMap(id){const spec=S7_ROOMS[id],map=parseMap(read(`../public/flare-s7/${spec.local}`));map.id=id;return map}

test('Screen 1 is the exact game invitation, not an instruction page',()=>{for(const marker of ['DUNGEON RUNNER','Your friend','has challenged you to select a dungeon for his Hero-Runner.','This takes only 30 seconds. Just accept the challenge and see his Hero run!','ACCEPT CHALLENGE'])assert.match(html,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));const first=html.slice(html.indexOf('class="receiver-screen invite-screen"'),html.indexOf('class="receiver-screen room-screen"'));assert.doesNotMatch(first,/HOW TO PLAY|Easy|Fair|Brutal|Goblin|Spike Trap/)});
test('safe sender fills the invitation name and strips markup',()=>{assert.equal(safeSender(' <Tom> '),'Tom');assert.equal(safeSender(''), 'Buddy');assert.equal(inviteSender('?from=%3CEve%3E'),'Eve');assert.match(html,/id="sender">Buddy/);assert.match(script,/inviteSender\(location\.search\)/)});
test('Screen 1 uses the real composed Flare stance animation',()=>{assert.match(script,/loadS3ActorPack/);assert.match(script,/startComposedHeroStance/);assert.match(preview,/sprites\?\.warrior/);assert.match(preview,/atlases\?\.warrior/);assert.match(preview,/animations\?\.stance/);assert.match(html,/canvas id="inviteHeroCanvas"/);assert.doesNotMatch(html,/inviteHeroCanvas[^>]+(?:src|background)=/)});
test('reduced motion pins the Hero to a stable stance frame',()=>{const animation={frames:3,duration:.1,type:'looped',entries:{'0:7':{id:0},'1:7':{id:1},'2:7':{id:2}}};assert.equal(heroStanceFrame(animation,0,false).id,0);assert.equal(heroStanceFrame(animation,.15,false).id,1);assert.equal(heroStanceFrame(animation,99,true).id,0);assert.match(preview,/if\(reducedMotion\)draw\(now\)/)});
test('accept only advances to dungeon selection and cannot start simulation',()=>{const handler=script.match(/\$\('accept'\)\.addEventListener\('click',\(\)=>goto\(1\)\)/)?.[0]||'';assert.ok(handler);assert.doesNotMatch(handler,/runGauntlet/);assert.match(script,/\$\('run'\)\.addEventListener\('click',runGauntlet\)/)});
test('customization is visibly optional in the hierarchy and build action',()=>{for(const marker of ['1 · CHOOSE A DUNGEON','2 · CUSTOMIZE THE DANGER — OPTIONAL','3 · RUN THE GAUNTLET','CUSTOMIZE DUNGEON — OPTIONAL','Skip customization and run now'])assert.match(html,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('novice path is Accept Challenge, Choose Dungeon, Run with calibrated defaults',()=>{assert.match(html,/id="accept"/);assert.match(html,/id="chooseRoom"[^>]*>CHOOSE DUNGEON/);assert.match(html,/id="run"[^>]*>RUN THE GAUNTLET/);assert.match(script,/applyEncounter\(calibrated\.encounter\)/);assert.match(script,/\$\('run'\)\.disabled=left<0\|\|!selectedRoom\(\)/);assert.doesNotMatch(script,/customize.*required/i)});
test('S7.1 retains all S7 content and controls without rebalance',()=>{assert.deepEqual(MONSTER_IDS,['goblin','skeleton','goblin-elite','antlion']);assert.deepEqual(TRAP_IDS,['spike-trap','dart-trap']);assert.deepEqual(SUPPORT_IDS,['small-potion','battle-tonic','iron-tonic']);for(const marker of ['100 gold','EASY','FAIR','BRUTAL','Goblin Elite','Antlion','Spike Trap','Dart Trap','Small Potion','Battle Tonic','Iron Tonic','OVERVIEW','PAUSE'])assert.match(html,new RegExp(marker,'i'))});
test('Level 3 Tough Warrior remains materially close to 60 percent',()=>{const runnerId='warrior-l3',targetHp=60,catalog=applyRunnerModel(base,model,runnerId),runner=runnerSummary(model,runnerId,catalog),cal=calibrateEncounter({catalog,model,runnerId,runner,targetHp}),id=Object.keys(S7_ROOMS)[0],map=roomMap(id),built=buildS7Challenge({roomId:id,roomTitle:S7_ROOMS[id].name,map,catalog,targetHp,encounter:cal.encounter,budget:100}),sim=new Simulation(map,built.challenge,catalog);sim.start();for(let i=0;i<3600&&sim.status==='running';i++)sim.step();const r=sim.result(),pct=actualHpPercent(r.status,r.hp,r.maxHp);assert.equal(cal.estimate.cost,100);assert.ok(Math.abs(pct-60)<=15,`${pct}%`)});
test('S7.1 invitations carry runner and target only in four k-route characters',()=>{const invite={runnerId:'warrior-l3',targetHp:60},code=encodeInviteCode(invite,model),decoded=decodeInviteCode(code,model),url=makeInviteUrl('https://think-2-thrive.com/quick-dungeon/flare-s71/',invite,model);assert.equal(code,'UvVY');assert.equal(code.length,4);assert.deepEqual({runnerId:decoded.runnerId,targetHp:decoded.targetHp},invite);assert.equal(url.href,'https://think-2-thrive.com/k/UvVY');assert.equal(makeInviteUrl('http://127.0.0.1:4171/quick-dungeon/flare-s71/',invite,model).href,'http://127.0.0.1:4171/k/UvVY');assert.equal(inviteCodeFromLocation({pathname:'/k/UvVY',search:''}),'UvVY');assert.doesNotMatch(JSON.stringify(decoded),/room|enemy|trap|support/i)});
test('S2 through S7 and prior route implementations are byte-for-byte unchanged',()=>{execFileSync('git',['diff','--quiet','4ca60cab1d14b8f7cc98087c49a72ad132310942','--','public/flare-s2','public/flare-s3','public/flare-s4','public/flare-s5','public/flare-s6','public/flare-s7']);for(const marker of ['/q/','/g/','/h/','/j/'])assert.doesNotMatch(builder+builderScript+html+script,new RegExp(marker.replace('/','\\/')));assert.match(html,/href="\/quick-dungeon\/flare-s71\/style\.css"/);assert.match(html,/src="\/quick-dungeon\/flare-s71\/challenge\.mjs"/)});
