import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {parseMap} from '../public/flare-p0/src/core/flare.mjs';import {deriveSlots,gridPath} from '../public/flare-s2/core.mjs';
import {S7_ROOMS,FLARE_115_PIN} from '../public/flare-s7/rooms.mjs';import {S7_ACTORS,requireS7AnimationStates} from '../public/flare-s7/actors.mjs';
import {ROOM_IDS,MONSTER_IDS,TRAP_IDS,SUPPORT_IDS,applyRunnerModel,runnerSummary,encounterCost,buildS7Challenge,actualHpPercent} from '../public/flare-s7/game.mjs';
import {Simulation} from '../public/flare-s7/simulation.mjs';import {calibrateEncounter,difficultyCue} from '../public/flare-s7/calibration.mjs';import {encodeInviteCode,decodeInviteCode,makeInviteUrl,inviteCodeFromLocation} from '../public/flare-s7/flow.mjs';

const readJson=path=>JSON.parse(fs.readFileSync(new URL(path,import.meta.url),'utf8')),base=readJson('../public/flare-p0/data/catalog.json'),model=readJson('../public/flare-s7/data/game.json');
const html=fs.readFileSync(new URL('../public/flare-s7/challenge.html',import.meta.url),'utf8'),builder=fs.readFileSync(new URL('../public/flare-s7/index.html',import.meta.url),'utf8'),script=fs.readFileSync(new URL('../public/flare-s7/challenge.mjs',import.meta.url),'utf8');
function roomMap(id){const spec=S7_ROOMS[id],map=parseMap(fs.readFileSync(new URL(`../public/flare-s7/${spec.local}`,import.meta.url),'utf8'));map.id=id;return map}
function run(id,encounter,{runnerId='warrior-l1',targetHp=50}={}){const map=roomMap(id),catalog=applyRunnerModel(base,model,runnerId),built=buildS7Challenge({roomId:id,roomTitle:S7_ROOMS[id].name,map,catalog,targetHp,encounter,budget:100}),sim=new Simulation(map,built.challenge,catalog);sim.start();for(let i=0;i<3600&&sim.status==='running';i++)sim.step();return{map,catalog,built,sim,result:sim.result()}}

test('S7 room registry is exactly the approved six-room matrix',()=>{assert.deepEqual(ROOM_IDS,Object.keys(S7_ROOMS));assert.equal(FLARE_115_PIN,'2ef474f5f5f368628bc526f9e56f936dac743e49');assert.deepEqual(ROOM_IDS.map(id=>S7_ROOMS[id].name),['Pillar Court','Crossed Court','Broken Gallery','Scattered Hall','Vaulted Crossing','Twin Lanes']);assert.deepEqual(ROOM_IDS.map(id=>S7_ROOMS[id].source),[1,3,7,8,15,18].map(n=>`mods/empyrean_campaign/maps/iron_labyrinth/room${n}.txt`))});
test('all six exact stock maps parse with supported collision and useful traversal',()=>{for(const id of ROOM_IDS){const map=roomMap(id),slots=deriveSlots(map,3);assert.equal(map.width,28);assert.equal(map.height,28);assert.ok(slots.pathLength>=6);assert.ok(gridPath(map,slots.spawn,slots.exit));assert.equal(new Set([slots.spawn,slots.exit,...slots.enemySlots,slots.potion].map(x=>x.join(','))).size,6)}});
test('all six rooms complete deterministic default simulations',()=>{for(const id of ROOM_IDS){const a=run(id,{enemyTypes:['goblin','skeleton','none'],supportTypes:['small-potion'],trapTypes:[]}),b=run(id,{enemyTypes:['goblin','skeleton','none'],supportTypes:['small-potion'],trapTypes:[]});assert.equal(a.result.status,'cleared',id);assert.deepEqual(a.result,b.result,id)}});
test('new stock actor registry uses the approved Flare definitions',()=>{assert.deepEqual(Object.keys(S7_ACTORS),['goblin-elite','antlion']);assert.equal(S7_ACTORS['goblin-elite'].source,'animations/enemies/goblin_elite.txt');assert.equal(S7_ACTORS.antlion.source,'animations/enemies/antlion.txt');assert.equal(S7_ACTORS['goblin-elite'].role,'Premium Striker');assert.equal(S7_ACTORS.antlion.role,'Durable Tank')});
test('S7 actor normalization requires real stance run swing hit and die',()=>{const frame={w:1,h:1},animations=Object.fromEntries(['stance','run','swing','hit','die'].map(k=>[k,{entries:{'0:0':{...frame}}}])),out=requireS7AnimationStates({animations},'probe');assert.equal(out.animations.attack,out.animations.swing);assert.throws(()=>requireS7AnimationStates({animations:{stance:animations.stance}},'broken'),/missing real run/)});
test('four monsters expose governed combat stats costs gold and roles',()=>{const catalog=applyRunnerModel(base,model,'warrior-l1');assert.deepEqual(MONSTER_IDS,Object.keys(model.monsters));assert.deepEqual([catalog.enemies['goblin-elite'].maxHp,catalog.enemies['goblin-elite'].damage,catalog.enemies['goblin-elite'].armor,catalog.enemies['goblin-elite'].cost,catalog.enemies['goblin-elite'].gold],[55,9,2,40,12]);assert.deepEqual([catalog.enemies.antlion.maxHp,catalog.enemies.antlion.damage,catalog.enemies.antlion.armor,catalog.enemies.antlion.cost,catalog.enemies.antlion.gold],[70,8,4,50,15]);assert.equal(model.monsters['goblin-elite'].role,'Premium Striker');assert.equal(model.monsters.antlion.role,'Durable Tank')});
test('two traps and three supports retain exact governed rules and readable cost',()=>{assert.deepEqual(TRAP_IDS,['spike-trap','dart-trap']);assert.deepEqual(SUPPORT_IDS,['small-potion','battle-tonic','iron-tonic']);assert.deepEqual([model.items['spike-trap'].damage,model.items['spike-trap'].cost,model.items['spike-trap'].armorPiercing],[30,20,false]);assert.deepEqual([model.items['dart-trap'].damage,model.items['dart-trap'].cost,model.items['dart-trap'].armorPiercing],[16,15,true]);for(const id of SUPPORT_IDS)assert.equal(model.items[id].cost,15)});
test('100-gold builder rejects overspend and makes every placement distinct',()=>{const catalog=applyRunnerModel(base,model,'warrior-l1'),legal={enemyTypes:['goblin','none','none'],supportTypes:[...SUPPORT_IDS],trapTypes:[...TRAP_IDS]},built=buildS7Challenge({roomId:ROOM_IDS[0],roomTitle:'Probe',map:roomMap(ROOM_IDS[0]),catalog,targetHp:50,encounter:legal});assert.equal(encounterCost(catalog,legal),100);assert.equal(built.spent,100);const positions=[built.challenge.spawn,built.challenge.exit,...built.challenge.enemies.map(x=>x.at),...built.challenge.items.map(x=>x.at)].map(x=>x.join(','));assert.equal(new Set(positions).size,positions.length);assert.throws(()=>buildS7Challenge({roomId:ROOM_IDS[0],roomTitle:'Probe',map:roomMap(ROOM_IDS[0]),catalog,targetHp:50,encounter:{enemyTypes:['antlion','antlion','antlion'],supportTypes:[],trapTypes:[]}}),/Budget exceeded/)});
test('Spike Trap applies defense while Dart Trap ignores defense and both fire once',()=>{const {sim,result}=run(ROOM_IDS[0],{enemyTypes:['goblin','none','none'],supportTypes:['iron-tonic'],trapTypes:[...TRAP_IDS]});const traps=sim.events.filter(x=>x.type==='trap');assert.equal(result.status,'cleared');assert.deepEqual(traps.map(x=>x.value),[27,16]);assert.deepEqual(traps.map(x=>x.armorPiercing),[false,true]);assert.equal(new Set(traps.map(x=>x.item)).size,2)});
test('Battle and Iron Tonics create actual rest-of-run combat bonuses',()=>{const {sim}=run(ROOM_IDS[0],{enemyTypes:['goblin','none','none'],supportTypes:['battle-tonic','iron-tonic'],trapTypes:[]});assert.equal(sim.hero.attackBonus,2);assert.equal(sim.hero.defenseBonus,2);assert.equal(sim.hero.damage,14);assert.equal(sim.hero.armor,3);assert.deepEqual(sim.events.filter(x=>x.type==='pickup'&&['attack','defense'].includes(x.kind)).map(x=>[x.kind,x.value]),[['attack',2],['defense',2]])});
test('Small Potion heals on its legal route position without duplication',()=>{const {sim}=run(ROOM_IDS[0],{enemyTypes:['skeleton','none','none'],supportTypes:['small-potion'],trapTypes:[]});const heals=sim.events.filter(x=>x.type==='pickup'&&x.kind==='heal');assert.equal(heals.length,1);assert.ok(heals[0].value>0&&heals[0].value<=10)});
test('new monsters are stationary melee guards with runtime swing attacks',()=>{for(const id of ['goblin-elite','antlion']){const {catalog,sim,result}=run(ROOM_IDS[0],{enemyTypes:[id,'none','none'],supportTypes:[],trapTypes:[]});assert.equal(catalog.enemies[id].behavior,'guard');assert.equal(catalog.enemies[id].range,1.08);assert.equal(result.status,'cleared');assert.ok(sim.events.some(x=>x.type==='attack'&&x.actor==='guard-1'));assert.ok(sim.events.some(x=>x.type==='attack'&&x.actor==='hero'))}});
test('S7 preserves coarse Easy Fair Brutal guidance and Level 3 60 calibration',()=>{const catalog=applyRunnerModel(base,model,'warrior-l3'),runner=runnerSummary(model,'warrior-l3',catalog),cal=calibrateEncounter({catalog,model,runnerId:'warrior-l3',runner,targetHp:60}),row=run(ROOM_IDS[0],cal.encounter,{runnerId:'warrior-l3',targetHp:60});assert.equal(cal.estimate.cost,100);assert.ok(Math.abs(actualHpPercent(row.result.status,row.result.hp,row.result.maxHp)-60)<=15);assert.deepEqual([difficultyCue(95,60).label,difficultyCue(66,60).label,difficultyCue(42,60).label],['Easy','Fair','Brutal'])});
test('S7 invitation carries runner and target only in four j-route characters',()=>{const invite={runnerId:'warrior-l3',targetHp:60},code=encodeInviteCode(invite,model),decoded=decodeInviteCode(code,model);assert.equal(code.length,4);assert.deepEqual({runnerId:decoded.runnerId,targetHp:decoded.targetHp},invite);assert.equal(makeInviteUrl('https://think-2-thrive.com/quick-dungeon/flare-s7/',invite,model).href,`https://think-2-thrive.com/j/${code}`);assert.equal(inviteCodeFromLocation({pathname:`/j/${code}`,search:''}),code)});
test('receiver keeps opening instructions three-touch path manual controls and all labels',()=>{for(const marker of ['HOW TO PLAY','Choose a room','Build the danger','Run the gauntlet','Easy','Fair','Brutal','CUSTOMIZE DUNGEON','Goblin Elite','Antlion','Small Potion','Battle Tonic','Iron Tonic','Spike Trap','Dart Trap','+10 HP','+2 ATK','+2 DEF','SPIKES','DARTS','1 / 6'])assert.match(html,new RegExp(marker.replace(/[+]/g,'\\+'),'i'),marker);assert.match(script,/pointerdown/);assert.match(script,/pointerup/);assert.match(script,/sim\.step\(\)/);assert.match(script,/scoreForTarget/)});
test('sender remains runner-and-target only and S7 uses canonical short-route assets',()=>{assert.doesNotMatch(builder,/id="roomPreview"|id="enemy1"|id="small-potion"|id="spike-trap"/);assert.match(builder,/You choose the runner and target/);assert.match(html,/href="\/quick-dungeon\/flare-s7\/style\.css"/);assert.match(html,/src="\/quick-dungeon\/flare-s7\/challenge\.mjs"/)});
