import test from 'node:test';import assert from 'node:assert/strict';
import {DEMO_LOGIN,DEFAULTS,validateDemoLogin,runnerSummary,makePlayerUrl,inviteSender,safeSender,encodeGauntletCode,decodeGauntletCode,gauntletCodeFromLocation} from '../public/flare-s3/flow.mjs';
const catalog={rules:'web-flare-0.2.0',heroes:{warrior:{maxHp:100,damage:12,armor:0}},enemies:{goblin:{cost:20,name:'Goblin'},skeleton:{cost:30,name:'Skeleton'}},items:{'small-potion':{cost:15}}};
const profile={id:'warrior-l1',hero:'warrior',name:'The Runner',className:'Warrior',level:1,weapon:'Wooden Club'};

test('demo login is intentionally bounded',()=>{assert.equal(validateDemoLogin(DEMO_LOGIN.username,DEMO_LOGIN.password),true);assert.equal(validateDemoLogin('buddy','Test'),false);assert.equal(validateDemoLogin('Buddy','wrong'),false)});
test('runner summary exposes simple novice combat stats',()=>{assert.deepEqual({...runnerSummary(profile,catalog)},{id:'warrior-l1',name:'The Runner',className:'Warrior',level:1,weapon:'Wooden Club',hero:'warrior',hp:100,attack:12,defense:0})});
test('novice defaults are balanced and under budget',()=>{const spent=20+30+15;assert.deepEqual(DEFAULTS.enemyTypes,['goblin','skeleton','none']);assert.equal(DEFAULTS.targetHp,50);assert.equal(DEFAULTS.roomId,'iron-labyrinth-01');assert.ok(spent<=DEFAULTS.budget)});
test('four-character gauntlet code round trips all novice choices',()=>{const input={roomId:'iron-labyrinth-15',enemyTypes:['skeleton','goblin','none'],potion:false,targetHp:70},code=encodeGauntletCode(input);assert.equal(code.length,4);assert.deepEqual({...decodeGauntletCode(code)},input)});
test('tampered compact code fails checksum',()=>{const code=encodeGauntletCode({roomId:DEFAULTS.roomId});const last=code.at(-1)==='A'?'B':'A';assert.throws(()=>decodeGauntletCode(code.slice(0,-1)+last),/checksum|Invalid/)});
test('HostGator player URL is ultra-short and separate from builder',()=>{const u=makePlayerUrl('https://think-2-thrive.com/quick-dungeon/flare-s3/',{roomId:DEFAULTS.roomId,enemyTypes:DEFAULTS.enemyTypes,potion:true,targetHp:50},{sender:'Buddy'});assert.match(u.href,/^https:\/\/think-2-thrive\.com\/q\/[A-Za-z0-9_-]{4}$/);assert.ok(u.href.length<40)});
test('compact code can be recovered from short route or fallback query',()=>{const code=encodeGauntletCode({roomId:DEFAULTS.roomId});assert.equal(gauntletCodeFromLocation({pathname:'/q/'+code,search:''}),code);assert.equal(gauntletCodeFromLocation({pathname:'/quick-dungeon/flare-s3/play.html',search:'?g='+code}),code)});
test('sender labels are bounded and sanitized',()=>{assert.equal(inviteSender('?from=Alex'),'Alex');assert.equal(inviteSender('?from=%3Cb%3EEve%3C%2Fb%3E'),'bEve/b');assert.equal(inviteSender('?from='),'Buddy');assert.equal(safeSender('<Buddy>'),'Buddy')});
