openapi: 3.1.0
info:
  title: Ruins Display API
  version: 1.0.2
servers:
  - url: https://ruins-api.vercel.app
paths:
  /api/display-room:
    get:
      operationId: displayRoom
      summary: Return markdown to render an image (room, transition, or map)
      description: |
        Returns **text/markdown**. The assistant must reply with this markdown verbatim so the image (including .webp animations) renders.
      parameters:
        - in: query
          name: name
          required: true
          description: Exact image name (e.g., "Room 3", "Room3to4", "Room 4", "Map").
          schema:
            type: string
            example: Room 3
      responses:
        "200":
          description: Markdown containing the image
          content:
            text/markdown:
              schema:
                type: string
        "404":
          description: Image not found
          content:
            text/plain:
              schema:
                type: string
