openapi: 3.1.0
info:
  title: Ruins API
  version: 1.0.0
paths:
  /api/display-room:
    get:
      operationId: getDisplayRoom
      summary: Get data for a specific room
      parameters:
        - in: query
          name: room
          schema:
            type: string
          required: true
          description: The room number to fetch
      responses:
        '200':
          description: Successful room data retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  image_url:
                    type: string
                  narration:
                    type: string
        '404':
          description: Room not found

