openapi: 3.1.0
info:
  title: Ruins Display API
  version: 1.0.0
servers:
  - url: https://ruins-api.vercel.app
paths:
  /api/display:
    get:
      operationId: display
      summary: Return markdown to render a room, a transition, or the map
      parameters:
        - in: query
          name: name
          required: true
          description: Accepts "Room 3", "Room 4", "Map", "Room3to4", or "Room4to3"
          schema:
            type: string
            enum: ["Room 3", "Room 4", "Map", "Room3to4", "Room4to3"]
      responses:
        "200":
          description: Markdown with an image tag for the requested resource
          content:
            text/markdown:
              schema:
                type: string
        "404":
          description: Resource not found
          content:
            text/plain:
              schema:
                type: string
