openapi: 3.1.0
info:
  title: Ruins Display API
  version: 1.1.0
servers:
  - url: https://ruins-api.vercel.app
paths:
  /api/display-room:
    get:
      operationId: displayRoom
      summary: Return markdown to render an image (room, transition, or map)
      description: |
        Returns **text/markdown** ONLY. The assistant must reply with the returned markdown verbatim
        (no extra words, no code fences) so the image renders cleanly.
      parameters:
        - in: query
          name: name
          required: true
          description: Exact image key, e.g., "Room 3", "Room3to4", "Map".
          schema:
            type: string
            examples: ["Room 3", "Room 4", "Room3to4", "Room4to3", "Map"]
      responses:
        "200":
          description: Markdown with the image
          content:
            text/markdown:
              schema:
                type: string
        "404":
          description: Image not found
          content:
            text/plain:
              schema:
                type: string
