openapi: 3.1.0
info:
  title: Ruins Display API
  version: 1.0.0
servers:
  - url: https://ruins-api.vercel.app
paths:
  /display-room:
    get:
      operationId: displayRoom
      parameters:
        - in: query
          name: name
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Markdown containing the image and narration
          content:
            text/markdown:
              schema:
                type: string
        "404":
          description: Room not found
          content:
            text/plain:
              schema:
                type: string
