openapi: 3.1.0
info:
  title: Ruins Display API
  version: 1.0.2
servers:
  - url: https://ruins-api.vercel.app
paths:
  /api/display-room:
    get:
      operationId: displayRoom
      summary: Return markdown to render an image (room, map, or transition)
      description: Returns clean markdown so the assistant can render the image directly without adding any text.
      parameters:
        - in: query
          name: name
          required: true
          description: Name of the image, e.g., "Room 3", "Room3to4", "Map".
          schema:
            type: string
            example: Room 3
      responses:
        "200":
          description: Markdown containing the image to render
          content:
            text/markdown:
              schema:
                type: string
        "404":
          description: Image not found
          content:
            text/plain:
              schema:
                type: string
